"use client";

import React from 'react';
import { HorenInteraktivTemplate } from '@/app/dashboard/HorenInteraktivTemplate';

const dictionary: Record<string, { meaning: string, type: string }> = {
    // Übung 1
    "was": { meaning: "Apa", type: "Kata Tanya" },
    "möchtest": { meaning: "ingin (dari möchten)", type: "Kata Kerja (Modal)" },
    "du": { meaning: "kamu", type: "Kata Ganti" },
    "nach": { meaning: "setelah", type: "Preposisi" },
    "der": { meaning: "itu (Artikel Dativ untuk die)", type: "Artikel" },
    "schule": { meaning: "sekolah", type: "Kata Benda" },
    "machen": { meaning: "melakukan / membuat", type: "Kata Kerja" },
    "ich": { meaning: "Saya", type: "Kata Ganti" },
    "weiß": { meaning: "tahu (dari wissen)", type: "Kata Kerja" },
    "es": { meaning: "itu (kata ganti netral)", type: "Kata Ganti" },
    "noch": { meaning: "masih", type: "Adverbia" },
    "nicht": { meaning: "tidak", type: "Partikel Negatif" },
    "genau": { meaning: "tepat / pasti", type: "Kata Sifat / Adverbia" },
    "früher": { meaning: "dulu / sebelumnya", type: "Adverbia" },
    "wollte": { meaning: "ingin (bentuk lampau dari wollen)", type: "Kata Kerja (Modal Präteritum)" },
    "medizin": { meaning: "kedokteran", type: "Kata Benda" },
    "studieren": { meaning: "kuliah / studi", type: "Kata Kerja" },
    "aber": { meaning: "tetapi", type: "Konjungsi" },
    "jetzt": { meaning: "sekarang", type: "Adverbia" },
    "denke": { meaning: "berpikir (dari denken)", type: "Kata Kerja" },
    "über": { meaning: "tentang", type: "Preposisi" },
    "eine": { meaning: "sebuah", type: "Artikel" },
    "ausbildung": { meaning: "pendidikan vokasi / magang", type: "Kata Benda" },
    "nachdenken": { meaning: "memikirkan", type: "Kata Kerja (Separable)" },
    "warum": { meaning: "kenapa", type: "Kata Tanya" },
    "weil": { meaning: "karena", type: "Konjungsi" },
    "praktisch": { meaning: "secara praktis", type: "Kata Sifat / Adverbia" },
    "arbeiten": { meaning: "bekerja", type: "Kata Kerja" },
    "durfte": { meaning: "diizinkan (bentuk lampau dari dürfen)", type: "Kata Kerja (Modal Präteritum)" },
    "letztes": { meaning: "terakhir / lalu", type: "Kata Sifat" },
    "jahr": { meaning: "tahun", type: "Kata Benda" },
    "ein": { meaning: "sebuah", type: "Artikel" },
    "praktikum": { meaning: "magang / praktik", type: "Kata Benda" },
    "im": { meaning: "di dalam (in + dem)", type: "Preposisi" },
    "krankenhaus": { meaning: "rumah sakit", type: "Kata Benda" },
    "war": { meaning: "adalah (bentuk lampau dari sein)", type: "Kata Kerja (To Be Präteritum)" },
    "toll": { meaning: "hebat / luar biasa", type: "Kata Sifat" },
    "studium": { meaning: "studi / perkuliahan", type: "Kata Benda" },
    "ist": { meaning: "adalah", type: "Kata Kerja (To Be)" },
    "mir": { meaning: "bagiku / kepadaku", type: "Kata Ganti (Dativ)" },
    "vielleicht": { meaning: "mungkin", type: "Adverbia" },
    "zu": { meaning: "terlalu", type: "Adverbia" },
    "theoretisch": { meaning: "teoretis", type: "Kata Sifat" },
    "meinung": { meaning: "pendapat", type: "Kata Benda" },
    "geändert": { meaning: "berubah / mengubah", type: "Kata Kerja (Partizip II)" },
    "langweilig": { meaning: "membosankan", type: "Kata Sifat" },
    "gesammelt": { meaning: "mengumpulkan", type: "Kata Kerja (Partizip II)" },
    "entscheidung": { meaning: "keputusan", type: "Kata Benda" },
    
    // Übung 2
    "guten": { meaning: "Selamat (seperti Selamat Pagi)", type: "Kata Sifat" },
    "tag": { meaning: "hari", type: "Kata Benda" },
    "herr": { meaning: "Tuan / Bapak", type: "Kata Benda" },
    "frau": { meaning: "Ibu / Nyonya", type: "Kata Benda" },
    "sie": { meaning: "Anda", type: "Kata Ganti (Formal)" },
    "interessieren": { meaning: "tertarik (sich interessieren)", type: "Kata Kerja Refleksif" },
    "sich": { meaning: "diri sendiri (refleksif)", type: "Kata Ganti" },
    "für": { meaning: "untuk", type: "Preposisi" },
    "das": { meaning: "itu (Artikel Netral)", type: "Artikel" },
    "in": { meaning: "di / ke dalam", type: "Preposisi" },
    "unserer": { meaning: "kita punya (Dativ Feminin)", type: "Kata Ganti Kepemilikan" },
    "it-abteilung": { meaning: "Departemen IT", type: "Kata Benda" },
    "ja": { meaning: "Ya", type: "Kata Seru" },
    "habe": { meaning: "memiliki (dari haben)", type: "Kata Kerja (Auxiliary)" },
    "gerade": { meaning: "baru saja", type: "Adverbia" },
    "mein": { meaning: "punyaku", type: "Kata Ganti Kepemilikan" },
    "abitur": { meaning: "Ijazah SMA Jerman (Abitur)", type: "Kata Benda" },
    "gemacht": { meaning: "melakukan / membuat (Partizip II)", type: "Kata Kerja" },
    "und": { meaning: "dan", type: "Konjungsi" },
    "informatik": { meaning: "Informatika", type: "Kata Benda" },
    "vor": { meaning: "sebelum", type: "Preposisi" },
    "dem": { meaning: "itu (Artikel Dativ)", type: "Artikel" },
    "praktische": { meaning: "praktis", type: "Kata Sifat" },
    "erfahrungen": { meaning: "pengalaman (Plural)", type: "Kata Benda" },
    "sammeln": { meaning: "mengumpulkan / mencari", type: "Kata Kerja" },
    "sehr": { meaning: "sangat", type: "Adverbia" },
    "gut": { meaning: "baik / bagus", type: "Kata Sifat" },
    "haben": { meaning: "mempunyai", type: "Kata Kerja" },
    "denn": { meaning: "lalu / sebab", type: "Partikel / Konjungsi" },
    "schon": { meaning: "sudah", type: "Adverbia" },
    "programmierkenntnisse": { meaning: "Pengetahuan Pemrograman", type: "Kata Benda" },
    "mit": { meaning: "dengan", type: "Preposisi" },
    "python": { meaning: "Python (Bahasa Pemrograman)", type: "Kata Benda" },
    "java": { meaning: "Java (Bahasa Pemrograman)", type: "Kata Benda" },
    "gearbeitet": { meaning: "bekerja (Partizip II dari arbeiten)", type: "Kata Kerja" },
    "platz": { meaning: "tempat / kursi", type: "Kata Benda" },
    "bisschen": { meaning: "sedikit", type: "Adverbia" },
    "büro": { meaning: "kantor", type: "Kata Benda" },

    // Übung 3
    "morgen": { meaning: "pagi", type: "Kata Benda" },
    "fehlt": { meaning: "kurang / sakit (Was fehlt Ihnen?)", type: "Kata Kerja" },
    "ihnen": { meaning: "Anda (Dativ)", type: "Kata Ganti" },
    "doktor": { meaning: "dokter", type: "Kata Benda" },
    "hals": { meaning: "leher / tenggorokan", type: "Kata Benda" },
    "tut": { meaning: "melakukan / membuat (wehtun = sakit)", type: "Kata Kerja" },
    "weh": { meaning: "sakit", type: "Kata Sifat" },
    "husten": { meaning: "batuk", type: "Kata Benda" },
    "verschreibe": { meaning: "meresepkan", type: "Kata Kerja" },
    "einen": { meaning: "sebuah (Akkusativ Maskulin)", type: "Artikel" },
    "sirup": { meaning: "sirup", type: "Kata Benda" },
    "dürfen": { meaning: "diizinkan / boleh", type: "Kata Kerja (Modal)" },
    "drei": { meaning: "tiga", type: "Angka" },
    "tage": { meaning: "hari-hari", type: "Kata Benda" },
    "lang": { meaning: "selama / panjang", type: "Adverbia" },
    "kalt": { meaning: "dingin", type: "Kata Sifat" },
    "kaltes": { meaning: "sesuatu yang dingin", type: "Kata Benda / Sifat" },
    "trinken": { meaning: "minum", type: "Kata Kerja" },
    "muss": { meaning: "harus", type: "Kata Kerja (Modal)" },
    "bett": { meaning: "tempat tidur", type: "Kata Benda" },
    "bleiben": { meaning: "tinggal / diam", type: "Kata Kerja" },
    "sollten": { meaning: "seharusnya", type: "Kata Kerja (Modal Präteritum)" },
    "ausruhen": { meaning: "beristirahat (sich ausruhen)", type: "Kata Kerja" },
    "gute": { meaning: "baik", type: "Kata Sifat" },
    "besserung": { meaning: "kesembuhan", type: "Kata Benda" },
    "fieber": { meaning: "demam", type: "Kata Benda" },
    "schlafen": { meaning: "tidur", type: "Kata Kerja" }
  };

export function HorenInteraktiv2() {
  return <HorenInteraktivTemplate kapitelId={2} dictionary={dictionary} />;
}

export default HorenInteraktiv2;
