"use client";

import React from 'react';
import { HorenInteraktivTemplate } from '@/app/dashboard/HorenInteraktivTemplate';

const dictionary: Record<string, { meaning: string, type: string }> = {
    // Übung 1
    "hallo": { meaning: "Halo", type: "Kata Seru" },
    "tut": { meaning: "Melakukan / Membuat", type: "Kata Kerja" },
    "mir": { meaning: "kepadaku (Dativ)", type: "Kata Ganti" },
    "leid": { meaning: "sedih / menyesal", type: "Kata Sifat" },
    "dass": { meaning: "bahwa", type: "Konjungsi" },
    "ich": { meaning: "Saya", type: "Kata Ganti" },
    "zu": { meaning: "terlalu / ke", type: "Preposisi / Adverbia" },
    "spät": { meaning: "terlambat", type: "Kata Sifat" },
    "bin": { meaning: "adalah (dari kata kerja 'sein')", type: "Kata Kerja (To Be)" },
    "kein": { meaning: "tidak ada / bukan", type: "Artikel Negatif" },
    "problem": { meaning: "masalah", type: "Kata Benda" },
    "was": { meaning: "Apa", type: "Kata Tanya" },
    "ist": { meaning: "adalah (dari kata kerja 'sein')", type: "Kata Kerja (To Be)" },
    "passiert": { meaning: "terjadi", type: "Kata Kerja (Partizip II)" },
    "mit": { meaning: "dengan", type: "Preposisi (Dativ)" },
    "dem": { meaning: "itu (Artikel Dativ untuk der/das)", type: "Artikel" },
    "bus": { meaning: "Bus", type: "Kata Benda" },
    "gefahren": { meaning: "mengendarai / bepergian", type: "Kata Kerja (Partizip II)" },
    "aber": { meaning: "tetapi", type: "Konjungsi" },
    "es": { meaning: "itu (kata ganti netral)", type: "Kata Ganti" },
    "gab": { meaning: "ada (dari 'es gibt' masa lampau)", type: "Kata Kerja (Präteritum)" },
    "einen": { meaning: "sebuah (Akkusativ)", type: "Artikel" },
    "stau": { meaning: "kemacetan", type: "Kata Benda" },
    "weil": { meaning: "karena", type: "Konjungsi" },
    "unfall": { meaning: "kecelakaan", type: "Kata Benda" },
    "autounfall": { meaning: "kecelakaan mobil", type: "Kata Benda" },
    "furchtbar": { meaning: "mengerikan / menakutkan", type: "Kata Sifat" },
    "gegeben": { meaning: "memberikan / ada", type: "Kata Kerja (Partizip II)" },
    "hat": { meaning: "memiliki", type: "Kata Kerja (Auxiliary)" },
    "oh": { meaning: "Oh", type: "Kata Seru" },
    "nein": { meaning: "Tidak", type: "Kata Seruan" },
    "hast": { meaning: "memiliki", type: "Kata Kerja (Auxiliary)" },
    "du": { meaning: "Kamu", type: "Kata Ganti" },
    "schon": { meaning: "sudah", type: "Adverbia" },
    "etwas": { meaning: "sesuatu", type: "Kata Ganti / Adverbia" },
    "gegessen": { meaning: "makan", type: "Kata Kerja (Partizip II)" },
    "ja": { meaning: "Ya", type: "Kata Seruan" },
    "habe": { meaning: "memiliki", type: "Kata Kerja (Auxiliary)" },
    "hause": { meaning: "rumah", type: "Kata Benda" },
    "pizza": { meaning: "Pizza", type: "Kata Benda" },
    "leckere": { meaning: "lezat", type: "Kata Sifat" },
    
    // Übung 2
    "entschuldigung": { meaning: "Permisi / Maaf", type: "Kata Seru / Kata Benda" },
    "haben": { meaning: "mempunyai", type: "Kata Kerja" },
    "sie": { meaning: "Anda (Formal)", type: "Kata Ganti" },
    "noch": { meaning: "masih", type: "Adverbia" },
    "käsekuchen": { meaning: "Kue Keju (Cheesecake)", type: "Kata Benda" },
    "der": { meaning: "itu (Artikel Maskulin)", type: "Artikel" },
    "leider": { meaning: "sayangnya", type: "Adverbia" },
    "aus": { meaning: "habis / dari", type: "Preposisi / Adverbia" },
    "schade": { meaning: "sayang sekali", type: "Kata Seru" },
    "wir": { meaning: "kita / kami", type: "Kata Ganti" },
    "apfelstrudel": { meaning: "Kue Apel (Apfelstrudel)", type: "Kata Benda" },
    "frischen": { meaning: "segar", type: "Kata Sifat" },
    "gut": { meaning: "baik", type: "Kata Sifat" },
    "dann": { meaning: "kalau begitu / kemudian", type: "Adverbia" },
    "nehme": { meaning: "mengambil (dari nehmen)", type: "Kata Kerja" },
    "ein": { meaning: "sebuah", type: "Artikel" },
    "stück": { meaning: "potong / bagian", type: "Kata Benda" },
    "und": { meaning: "dan", type: "Konjungsi" },
    "kaffee": { meaning: "Kopi", type: "Kata Benda" },
    "bitte": { meaning: "tolong", type: "Kata Seru" },
    "möchten": { meaning: "ingin", type: "Kata Kerja (Modal)" },
    "milch": { meaning: "Susu", type: "Kata Benda" },
    "zucker": { meaning: "Gula", type: "Kata Benda" },
    "nur": { meaning: "hanya", type: "Adverbia" },
    "trinke": { meaning: "minum (dari trinken)", type: "Kata Kerja" },
    "keinen": { meaning: "tidak (Akkusativ)", type: "Artikel Negatif" },
    "sofort": { meaning: "segera", type: "Adverbia" },

    // Übung 3
    "zug": { meaning: "Kereta", type: "Kata Benda" },
    "münchen": { meaning: "Munich (Kota)", type: "Kata Benda" },
    "abgefahren": { meaning: "berangkat (Partizip II)", type: "Kata Kerja" },
    "minuten": { meaning: "menit", type: "Kata Benda" },
    "ungefähr": { meaning: "sekitar / kira-kira", type: "Adverbia" },
    "verspätung": { meaning: "keterlambatan", type: "Kata Benda" },
    "vielleicht": { meaning: "mungkin", type: "Adverbia" },
    "technisches": { meaning: "teknis", type: "Kata Sifat" },
    "signal": { meaning: "sinyal", type: "Kata Benda" },
    "vielen": { meaning: "banyak", type: "Kata Sifat" },
    "dank": { meaning: "terima kasih", type: "Kata Benda" },
    "information": { meaning: "informasi", type: "Kata Benda" },
    "wissen": { meaning: "tahu", type: "Kata Kerja" },
    "wo": { meaning: "dimana", type: "Kata Tanya" },
    "gleis": { meaning: "peron / jalur kereta", type: "Kata Benda" },
    "müssen": { meaning: "harus", type: "Kata Kerja (Modal)" },
    "einfach": { meaning: "mudah / cukup", type: "Adverbia" },
    "treppe": { meaning: "tangga", type: "Kata Benda" },
    "runtergehen": { meaning: "turun (berjalan)", type: "Kata Kerja" },
    "gleich": { meaning: "langsung / segera", type: "Adverbia" },
    "rechts": { meaning: "kanan", type: "Adverbia" },
    "da": { meaning: "di sana", type: "Adverbia" }
  };

export function HorenInteraktiv1() {
  return <HorenInteraktivTemplate kapitelId={1} dictionary={dictionary} />;
}

export default HorenInteraktiv1;
